- scm:
    name: git-ui-autotests
    scm:
    - git:
        url: https://github.com/Butakov55/homeworkOtus1.git
        credentials-id: jenkins
        branches:
        - FETCH_HEAD
        refspec: ${BRANCH}