---
- view:
    name: QA
    view-type: list
    description: |
      QA jobs
    filter-executors: true
    filter-queue: true
    job-name:
      -'ui-autotests'
    columns:
      - status
      - wather
      - job
      - last-success
      - last-failure
      - last-duration
      - build-button