- job-template:
    name: 'ui-autotests'
    description: 'Running UI autotests'
    project-type: pipeline
    concurrent: true
    parameters:
      - string:
          name: BRANCH
          default: Homework-4
          description: "Branch for tempest UI OTUS tests"
      - string:
          name: BASE_URL
          default: https://otus.ru
          description: "Hostname of stand"
      - string:
          name: BROWSER_NAME
          default: chrome
          description: "Browser name"
      - string:
          name: BROWSER_VERSION
          default: "101.0"
          description: "Browser version"
    pipeline-scm:
      scm:
      - git-ui-autotests
      script-path: jenkins/ui-autotests.groovy